### ISSUE TITLE
a bug ? - how to false buildin 'hud'

### ISSUE THREAD

**Issue by Festus1965** [MultiCraft/MultiCraft2#15]
##### Minetest version
2.0.0 on 5.4.1 fork

##### OS / Hardware
on two server diff, both Ubuntu 20.04

##### Summary
at test, I make (local) and after change init.lua in builtin without do hud / hunger, and even delete them both not started
at main server, I did sudo make install but found the buildin in usr/local/share/multicraft, did the same change in init.lua NOT to start hunger and hud, also did it for safety in source MultiCraft2 folder with the cmake, make ... but hud still starts with and so I have warnings when my hud works and logins

so where else could the start of hud from MultiCraft been hidden ?

##### Steps to reproduce
see above

**Comment by MoNTE48** [comment]
Just `enable_hunger = false` in your `.conf`.
https://github.com/MultiCraft/MultiCraft2/blob/main/builtin/game/hunger.lua#L24

**Comment by Festus1965** [comment]
did that, as I also had done in testing envoirenment, without usr/loval/share/...

...conf:
enable_hunger = false

but just as another crash I got at starting:
2021-09-11 18:03:20: ERROR[Main]: [mod] hud_hunger / hud [error]: A statbar with that name already exists

now, I also added:
enable_hud = false

and see what your suggestion is.

**Comment by MoNTE48** [comment]
This mod is built into MultiCraft.
You can't disable it and you don't have to.

**Comment by MoNTE48** [comment]
And any reason why you want to do this?
Also, please use Google Translate or ask someone to help you. Your English is a collection of unrelated words and you cannot be understood.

**Comment by Festus1965** [comment]
> This mod is built into MultiCraft.
> You can't disable it and you don't have to.

I WAS able to disable it (both: hunger and hud) on a RUN_IN_PLACE ? installation (not using /usr/local/... )
so IT IS possible

but it is not possible now under the installation used 'sudo make -j6 install' - that is wondering me.
I want to do it, as deactivate the builtin (mods: hud, hunger) would keep my configuration as most as it was.


or with translate:
I want to disable the mods because it has worked before. The difference is simply the type of installation, but strangely I can't reproduce that.
I want to keep my original mods to keep the year-old server as authentic as possible, even under Multicraft.

**Comment by Festus1965** [comment]
here it works with comment out and delete:
`MultiCraft 2.0.0 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=0
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"`

here not:
`MultiCraft 2.0.0 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=0
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/local/share/multicraft"
STATIC_LOCALEDIR="/usr/local/share/locale"
`

**Comment by Festus1965** [comment]
so I solved the different installation issue:
the DRUN_IN_PLACE=1 must be after the final . (dot) of cmake

the rest I find out then myself also, seam to be better

**Comment by Festus1965** [comment]
even e builtin mod can be deactivated, so I have to to my own fork then maybe if no help
