### ISSUE TITLE
I call it bug, when mobile android / IPAD useer have 9 slot, but server ignore nr 9

### ISSUE THREAD

**Issue by Festus1965** [MultiCraft/MultiCraft2#18]
##### Minetest version
```
multicraft2.0.0 server - and I don't know versions multicraft on android / IPAD
```

##### OS / Hardware
CPU: ignore

GPU model: ignore
OpenGL version: ignore

##### Summary
mobile android / IPAD user have like Slot 9
server tell in terminal : ignoring ...
but gamer is able to build himself up with not seen or detectable nodes

##### Steps to reproduce
lol, your the programmer ... that's funny : both multicraft but different set of slots

**Comment by MoNTE48** [comment]
Right. The MultiCraft client for Android / iOS has a hardcoded interface with 9-slots HUD bar.
This is probably not the best solution, but no one is going to change that as far as I know.

**Comment by Festus1965** [comment]
lol,
it is possible to allow it inside mt / mc server ? ... I search a bit around, but couldn't see a value like 8 set for hud, seam also hardcoded ?

**Comment by MoNTE48** [comment]
You cannot change this for mobile MultiCraft players. Only 9 slots, this is a hard value.
I recommend to just use 9 slots for all players or add version-based client validation (`1.0.0`-`1.99.99`) and set their HUD size to 9 slots.

**Comment by Festus1965** [comment]
ok, then BYE
