### ISSUE TITLE
`/status` chatcommand does't display a list of installed mods

### ISSUE THREAD

**Issue by Festus1965** [MultiCraft/MultiCraft2#19]
## Problem

I miss /status
as of easier to see the lag,
and other side the logged in gamer

and one mod technic, might change then it's behavior ir higher (had to change code there)

Not only me ... some gamer miss also

## Solutions

Where did you cut that out, I struggle at get_ ...(status,true) command in chat, builtin ... to track back,
even compare with mt 5.3.0 was not successful yet

## Alternatives

I see a maybe mod for the gamer logged in, have to try else ...

## Additional context

Reason you disabled this ?
or did I make a unseen setting, as .conf, I don't see ?
The lag and gamer are anyway listed in servers. ... .

**Comment by MoNTE48** [comment]
The less an attacker knows about you, the safer you are.
The output of the list of mods is disabled on the engine side for security later with multiple attacks by an unknown group of persons using vulnerabilities in the mods.

There are no settings for this. Changes were made on the Engine side (C++).
`git log` or `git grep` can help you find the commit you want and revert the change if you want.

**Comment by Festus1965** [comment]
is there a misunderstanding ?
* I meant /status = show lag and gamer
* /mods is another commend, that I didn't mean, but also all mods are seen easy in servers.m....
so you think not get this ata in gamer, that person would NOT check via servers.m ... ?

**Comment by MoNTE48** [comment]
Oh, this information (list of players online) was also used for spam in PM and was therefore disabled. Bad people spammed offensive things to all online players and the moderators couldn't see it.

**Comment by Festus1965** [comment]
lol, at the end after a research about
multicraft, owners, distributors
I found too much hidden companies, empty pages 
and as even some multicraft see ads (there is not only one called multicraft)
and the multicraft use the slot9 to build towers to climb up virtual
and as after ask all gamer, and the answering ones accept ads,

I decided NOT any longer to support clients with ads, and slot9
= not supporting money for others with my costs of electric and time, hardware

= I am back to MT 5.x for a while,
until and can stop MT at all, (2022)
keep my proposal after got money to keep the server minimum a year after the payment.

BYE
