### ISSUE TITLE
9th slot issue

### ISSUE THREAD

**Issue by ViniProTheBro** [MultiCraft/MultiCraft2#27]
the 9th slot is an issue in (as far as i know) almost all minetest servers that can run multicraft.
it cant be modified to a diffrent amount for example the default number of minetest 8, and allows the client to locally place blocks untill they have placed a block that is not in the 9th slot which basicly makes it client sided flying for survival servers and gives building issues on creative servers. would highly be appriciated if you could just allow servers to modify inventory slots so this wouldn't be an issue.

(proof from somone on discord)

https://user-images.githubusercontent.com/57672251/150652991-54257e34-882f-4e05-a01e-9a13c3887e93.mov

**Comment by MoNTE48** [comment]
This problem was fixed more than 2 months ago. It is recommended to always use the latest version of MultiCraft 2.0 Engine.

https://github.com/MultiCraft/MultiCraft2/commit/d6b01ab8ef1c765620bdcd992c22d74e284470b3
