### ISSUE TITLE
0 fps after a short time on IOS multicraft and PC minetest v=0.4.17.1

### ISSUE THREAD

**Issue by git512** [MultiCraft/MultiCraft2#8]
##### Minetest version

```
MultiCraft 2.0.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
git hash:
4fbfe9443b09ff35fe1c7cd9e7017ac8cbe418cc
```

##### OS / Hardware

Operating system: 

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

CPU:
server:
model name      : Intel(R) Core(TM)2 Quad CPU    Q6700  @ 2.66GHz

GPU model: multiple (clients)
OpenGL version:

##### Summary

PC minetest 0.4.17.1 and IOS multicraft clients are experiencing massive fps drop leading to the game going unresponsive.

PC minetest 5.4 has none such issue on the same hardware and OS

PC minetest 0.4.17.1 complains about:
2021-06-09 20:59:28: INFO[Main]: collisionMoveSimple: maximum step interval exceeded, lost movement details!
Not sure if relevent.

##### Steps to reproduce

I'm trying to run my potatoland world on multicraft.  This world has a LOT of mods. Server wise it seems to run great and current minetest PC client runs smooth on it but most of my players are mobile multicraft players.

**Comment by MoNTE48** [comment]
Hello. This clearly has nothing to do with this repository.
iOS client does not use this code. iOS client still based on Minetest 0.4.17.

**Comment by git512** [comment]
As stated: the server is running this repo so clearly it has /something/ to do with it and the issue doesn't occur with an MT 0.4.17.1 server.  Responses like such are unhelpful and honestly somewhat hurtful. I'm just trying to have a discussion with the people that might have some clue what the issue is.

Does this mean that MultiCraft 2 is now a dead project? Is there another that offers the same general 0.4/5.x compatibility?

I'm just looking for insight on moving my server to a more up to date code base and newer mods without shunning players who have spent countless hours building there. I still have players that have been playing since the night my server went up almost 3 years ago.  That's what we're doing here right? Trying to give people something cool to play?  

Multicraft2 seemed like a pretty good option.  It runs the world and mods (with minimal changes to the mod base) and seemed to allow both MT 0.4.x branches and 5.x branches to use it although with the issue of a fps drop to zero a few to several minutes in on 0.4.x clients (which apparently mobile (IOS only?) Multicraft clients are).

I'm just looking for a way forward.  Any actionable input is greatly appreciated. I'm not trying to annoy anyone but as the same time I am looking for a path forward that can be achieved with the time I have to give outside of a full time workload.


As to the update:
I'm honestly not sure why a 0.4.x client would be complaining about it or what could be done as a workaround.

Sorry for the wall of text. Just looking for options.  Thanks a bunch for reading.

**Comment by sangeet79** [comment]
I confirm the problem, described by @git512. I run multicraft 2.0.0. on Arch Linux. 
All players with iOS multicraft 1.16.2. have fps drops to zero level with them eventually timing out of the game. They didn't have this problem a few weeks ago. It seems that the problem appeared after the last client update. Android players with 1.15.8. have no such problems. I have not tested the old 0.4.17.1 PC minetest version, but I am sure to get the same results as @git512

**Comment by MoNTE48** [comment]
@sangeet79 Knowing which server we are talking about (ip:port), I could test it myself.

Well, the secret is that 1.15.8 and 1.16.2 have no changes. We use different version numbering on different platforms.

**Comment by sangeet79** [comment]
@MoNTE48 oh, i see. I will ask people for iOS versions and device models. One is using IPhone 8 Plus.
server av.edgy1.net:48146
Currently i am over the area where people experience fps drops.

**Comment by MoNTE48** [comment]
@sangeet79 can you find me in discord?
MoNTE48#4444

**Comment by sangeet79** [comment]
Ok, @MoNTE48 tested using several iPhone devices, there was no problem. Perhaps this is the memory problem with player devices. I will check this issue with them.

**Comment by git512** [comment]
I'm now even more confused. I copied over the world folder of a new world I've been working on called "Infinity One" (IO for short)

It is using the exact same mod base, same hardware and a duplicated world.mt file from my tests with PotatoLand and 0.4.17 based clients (pc minetest included) run it great. 

IO has less than 100 hours of player time on it and therefore much less building has been done on it but outside of the world folder being different, the server config and codebase should be identical.

This world is live on the same address as PL (mtpotatoland.us.to) on port 40000 if it would be helpful to check it out.

**Comment by git512** [comment]
Just to note: when I was experiencing this issue on a PC client it was on a rig with 16GB of ram. Task manager showed nothing out of the ordinary for minetest as far as ram or processor usage.

**Comment by MoNTE48** [comment]
@git512 please find me on Discord (`MoNTE48#4444`) or in Telegram (https://t.me/MoNTE48)

**Comment by luk3yx** [comment]
This is very strange. Is there any big difference (perhaps entities) between the two worlds?

> PC minetest 0.4.17.1 complains about:
> 2021-06-09 20:59:28: INFO[Main]: collisionMoveSimple: maximum step interval exceeded, lost movement details!
> Not sure if relevent.

That log message seems to occur when the game is running at less than 2 FPS (https://github.com/MultiCraft/MultiCraft-legacy/blob/master/src/collision.cpp#L232-L238).

**Comment by 0siribix** [comment]
> Hello. This clearly has nothing to do with this repository.
> iOS client does not use this code. iOS client still based on Minetest 0.4.17.
> Update. I'm sure that `collisionMoveSimple` metod is not supported in Minetest 0.4.17 and we do not plan to fix this. MultiCraft 2 (based on MT5.3) is discontinued.

Does this mean that the server or client or both are discontinued?

**Comment by mckaygerhard** [comment]
> ... MultiCraft 2 (based on MT5.3) is discontinued.

err and then waht is the suported one? also i find some ambogous references to minetest to just "be according to the original license"
