### ISSUE TITLE
Readme should explain where to download binaries and find servers

### ISSUE THREAD

**Issue by mk-pmb** [MultiCraft/MultiCraft2#9]
I cannot find download instructions in the readme's table of contents, and everything in the "Further documentation" section is about MineTest. Even here this bug template asks me for my MineTest version. Which confuses me, because I'm trying to find binary downloads for MultiCraft. Or do I use my already-installed MineTest client to play MultiCraft?

Also I need advice on how to find servers, because my search engine strongly prefers the Minecraft hosting manager thingy that happens to also be named Multicraft.

**Comment by MoNTE48** [comment]
We do not distribute MultiCraft 2.0 binaries, we only publish the source code. Anyone can compile it if they are interested.
We only use this source code as a server on our Linux machines.

**Comment by mk-pmb** [comment]
In that case, the readme should have a "Download" chapter that explains that currently, there are no official binary downloads.

**Comment by MoNTE48** [comment]
@mk-pmb, perhaps, but I don't have time to do this.
We just publish the source code to comply with the license.

**Comment by mckaygerhard** [comment]
i will take your word @MoNTE48  and wil try to compile in both linux and androit.. but as i noted the instructions are not so clear.. but i **will post feedback here with pull request.. thanks**

**Comment by mckaygerhard** [comment]
> We do not distribute MultiCraft 2.0 binaries, we only publish the source code. Anyone can compile it if they are interested. We only use this source code as a server on our Linux machines.

as @mk-pmb said the readme are pretty vage, the instructions are inside docs/readme.md but there's no references and the format are windoser made.. also i cannot confirm any information from readme cos multicraft raised an error: due #44 

Readme are there only to complain with license etc etc i guess right?

also bug issue said "mientest version" but this is multicraft.. and in #8 said that is not supported.. i guess this project is more privative rather people guess and try to olny guess money

if there not as i said and i am wrong i can send a pull request and you at least take and improved the readme file

if not can you help me to improve and clarify the issues? @MoNTE48 ?

**Comment by mckaygerhard** [comment]
i also find that commit https://github.com/MultiCraft/MultiCraft2/commit/5722b9ad23a8c8a0b43ff6efc51d6c85609e166f embebed the minecraft server list as base64 string..

**Comment by MoNTE48** [comment]
@mckaygerhard I'm sorry, but I just don't understand you. You use random English words. But they don't make any sense to me...

**Comment by mckaygerhard** [comment]
> @mckaygerhard I'm sorry, but I just don't understand you. You use random English words. But they don't make any sense to me...

you dont understand me maybe cos @[mu](https://github.com/MultiCraft) deleted an important message but i guess cannot deleted from the forum? can be you more respectfully with users and be more transparent? @MoNTE48  ?

![imagen](https://user-images.githubusercontent.com/1571724/157878958-b82dc0fe-9048-4c62-88bc-fc5dce2f83c8.png)

you also still referenced and SEND the servers to the list of minetest server..

**Comment by MoNTE48** [comment]
Please, this is not the place for discussion. Report a problem or bug, or don't engage in offtopic. Otherwise you will be banned from this repository.

**Comment by mckaygerhard** [comment]
the issue is about README ok, i sadi that the readme is not clear for the users.. by example #44 only said path but must be "full path to the file lib" event only "full path" .. and there's another lilttle issues of course.. this can be improved.. 

also @MoNTE48  about the reference i'll open a new issue.. that's true but it seems the response without explanation seems more like an agression due your response very intimidate!

**Comment by MoNTE48** [comment]
You can PM me in Telegram, if you want.
https://t.me/MoNTE48

**Comment by mckaygerhard** [comment]
Thanks @MoNTE48  i like the telegram

**Comment by mckaygerhard** [comment]
Thanks @MoNTE48 i like the telegram, but i cannot find you .. can you pm me @mckaygerhard ?
